language: cpp

matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    compiler: clang

    script:
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild -configuration Debug
      - xcodebuild -configuration Release

    deploy:
      provider: releases
      skip_cleanup: true
      file: "build/*/*.zip"
      file_glob: true
      api_key:
        secure: EjPoUSY64lSp9uWz9+4Keut++xaUd+6gnjwXhCN2k0MutvJGfj65EcJPb6J3x/wXqfBPDko1UmctKSe/pJsFw60cf3asNZIRV0Fur+IN428yy/VoIV4SXPzXhnegD2XWoMDWJqg7Dt+nD31kL1D8x+TkbK75CjnorHqnZODEC/T7RyfICWuu9/JyKOwu8XfdtVhbomohpQZyib6xZJYjdLCcHgGCB3gehADG0amSHRxiGEx63p3vK6dEJvBLjo+jCAYZHYbKFvedORq6ckjBQ1KS2ulqOygt2Net9+ReVGCsm2X88eVqjjb5K5ilF/kobf5Tyf7/UoDnXBHiAa6BE5cjXmWvEM9b7m+MqjQqHy8TIRMHPXassyCDUflmMU8TeZM4PNig6CvsNO0nHS1loO0+RMGkwnW51xdP+m8ISBddip/eQfFP5opQ+HktreQ8CVp2GAsD0g4hSVGazyFaoIrQiSeGEW/WqYKS1S/zAArLgFFAcYHo3oekSiOZZCZXny4mHKmk2esUwtSwQNumF5GYQo43kZ7EgunJb+fm8/MJQrD7SJuF6ejK9qMyQgHhWcCchuiOn6bnfSVh9jYwyJ9Hq4EftPxhik/u0AiRPEUquwFZuLpm6jouCC2nwohF0E0T5UUIUHZdkhab46h3wEE5gjVx9ZIw0E6dR2vSeGg=
      on:
        tags: true
  - os: osx
    osx_image: xcode10.2
    compiler: clang

    script:
      - src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1
      - xcodebuild analyze -quiet -scheme AppleALC -configuration Debug CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
      - xcodebuild analyze -quiet -scheme AppleALC -configuration Release CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
